name: Prova de camara copia
description: This example showcases object detection within a live feed from a USB camera.
ports: []
bricks:
- arduino:video_object_detection: {}
- arduino:web_ui: {}
- arduino:dbstorage_sqlstore: {}
- arduino:audio_classification:
    model: ei-model-991592-1
icon: 📽️
